from models.player_match_stat import PlayerMatchStat
from orm.player_match_stat import PlayerMatchStatORM


def player_match_stat_to_orm(stat: PlayerMatchStat) -> PlayerMatchStatORM:
    return PlayerMatchStatORM(
        id=stat.id,
        match_id=stat.match_id,
        fotmob_match_id=stat.fotmob_match_id,
        team_id=stat.team_id,
        fotmob_player_id=stat.fotmob_player_id,
        player_name=stat.player_name,
        is_goalkeeper=stat.is_goalkeeper,
        is_home=stat.is_home,
        rating=stat.rating,
        minutes_played=stat.minutes_played,
        goals=stat.goals,
        assists=stat.assists,
        xG=stat.xG,
        xA=stat.xA,
        xG_non_penalty=stat.xG_non_penalty,
        xG_on_target_faced=stat.xG_on_target_faced,
        xG_on_target_variant=stat.xG_on_target_variant,
        xG_plus_xA=stat.xG_plus_xA,
        total_shots=stat.total_shots,
        shots_on_target=stat.shots_on_target,
        shots_off_target=stat.shots_off_target,
        shot_accuracy=stat.shot_accuracy,
        blocked_shots=stat.blocked_shots,
        shots_woodwork=stat.shots_woodwork,
        touches=stat.touches,
        touches_opposition_box=stat.touches_opposition_box,
        passes_into_final_third=stat.passes_into_final_third,
        accurate_passes=stat.accurate_passes,
        accurate_crosses=stat.accurate_crosses,
        long_balls_accurate=stat.long_balls_accurate,
        corners=stat.corners,
        dispossessed=stat.dispossessed,
        chances_created=stat.chances_created,
        big_chances_created=stat.big_chances_created,
        defensive_actions=stat.defensive_actions,
        tackles=stat.tackles,
        interceptions=stat.interceptions,
        clearances=stat.clearances,
        headed_clearances=stat.headed_clearances,
        recoveries=stat.recoveries,
        duels_won=stat.duels_won,
        duels_lost=stat.duels_lost,
        ground_duels_won=stat.ground_duels_won,
        aerials_won=stat.aerials_won,
        dribbles_succeeded=stat.dribbles_succeeded,
        fouls=stat.fouls,
        was_fouled=stat.was_fouled,
        offsides=stat.offsides,
        dribbled_past=stat.dribbled_past,
        saves=stat.saves,
        saves_inside_box=stat.saves_inside_box,
        goals_conceded=stat.goals_conceded,
        goals_prevented=stat.goals_prevented,
        keeper_diving_saves=stat.keeper_diving_saves,
        keeper_high_claims=stat.keeper_high_claims,
        keeper_sweeper_actions=stat.keeper_sweeper_actions,
        punches=stat.punches,
        errors_led_to_goal=stat.errors_led_to_goal,
        player_throws=stat.player_throws,
    )
