from models.team_match_stat import TeamMatchStat
from orm.team_match_stat import TeamMatchStatORM


def team_match_stat_to_orm(stat: TeamMatchStat) -> TeamMatchStatORM:
    return TeamMatchStatORM(
        id=stat.id,
        match_id=stat.match_id,
        fotmob_match_id=stat.fotmob_match_id,
        team_id=stat.team_id,
        is_home=stat.is_home,
        ball_possession=stat.ball_possession,
        expected_goals=stat.expected_goals,
        total_shots=stat.total_shots,
        shots_on_target=stat.shots_on_target,
        touches_opposition_box=stat.touches_opposition_box,
        big_chances=stat.big_chances,
        big_chances_missed=stat.big_chances_missed,
        accurate_passes=stat.accurate_passes,
        yellow_cards=stat.yellow_cards,
        corners=stat.corners,
        shots_off_target=stat.shots_off_target,
        blocked_shots=stat.blocked_shots,
        shots_woodwork=stat.shots_woodwork,
        shots_inside_box=stat.shots_inside_box,
        shots_outside_box=stat.shots_outside_box,
        expected_goals_open_play=stat.expected_goals_open_play,
        expected_goals_set_play=stat.expected_goals_set_play,
        expected_goals_non_penalty=stat.expected_goals_non_penalty,
        expected_goals_on_target=stat.expected_goals_on_target,
        passes=stat.passes,
        own_half_passes=stat.own_half_passes,
        opposition_half_passes=stat.opposition_half_passes,
        long_balls_accurate=stat.long_balls_accurate,
        accurate_crosses=stat.accurate_crosses,
        player_throws=stat.player_throws,
        offsides=stat.offsides,
        tackles=stat.tackles,
        interceptions=stat.interceptions,
        shot_blocks=stat.shot_blocks,
        clearances=stat.clearances,
        keeper_saves=stat.keeper_saves,
        duels_won=stat.duels_won,
        ground_duels_won=stat.ground_duels_won,
        aerials_won=stat.aerials_won,
        dribbles_succeeded=stat.dribbles_succeeded,
        red_cards=stat.red_cards,
        fouls=stat.fouls,
    )
