from sqlalchemy import String, Integer, BigInteger, Boolean, Float
from sqlalchemy.orm import Mapped, mapped_column
from database.base import Base


class PlayerMatchStatORM(Base):
    __tablename__ = "player_match_stats"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    match_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    fotmob_match_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    team_id: Mapped[int] = mapped_column(Integer, nullable=False)
    fotmob_player_id: Mapped[int] = mapped_column(Integer, nullable=False)
    player_name: Mapped[str] = mapped_column(String(100), nullable=False)
    is_goalkeeper: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_home: Mapped[bool] = mapped_column(Boolean, nullable=False)

    rating: Mapped[float | None] = mapped_column(Float, nullable=True)
    minutes_played: Mapped[float] = mapped_column(
        Float, nullable=False, server_default="0"
    )
    goals: Mapped[float | None] = mapped_column(Float, nullable=True)
    assists: Mapped[float | None] = mapped_column(Float, nullable=True)
    xG: Mapped[float | None] = mapped_column(Float, nullable=True)
    xA: Mapped[float | None] = mapped_column(Float, nullable=True)
    xG_non_penalty: Mapped[float | None] = mapped_column(Float, nullable=True)
    xG_on_target_faced: Mapped[float | None] = mapped_column(Float, nullable=True)
    xG_on_target_variant: Mapped[float | None] = mapped_column(Float, nullable=True)
    xG_plus_xA: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_shots: Mapped[float | None] = mapped_column(Float, nullable=True)
    shots_on_target: Mapped[float | None] = mapped_column(Float, nullable=True)
    shots_off_target: Mapped[float | None] = mapped_column(Float, nullable=True)
    shot_accuracy: Mapped[float | None] = mapped_column(Float, nullable=True)
    blocked_shots: Mapped[float | None] = mapped_column(Float, nullable=True)
    shots_woodwork: Mapped[float | None] = mapped_column(Float, nullable=True)
    touches: Mapped[float | None] = mapped_column(Float, nullable=True)
    touches_opposition_box: Mapped[float | None] = mapped_column(Float, nullable=True)
    passes_into_final_third: Mapped[float | None] = mapped_column(Float, nullable=True)
    accurate_passes: Mapped[float | None] = mapped_column(Float, nullable=True)
    accurate_crosses: Mapped[float | None] = mapped_column(Float, nullable=True)
    long_balls_accurate: Mapped[float | None] = mapped_column(Float, nullable=True)
    corners: Mapped[float | None] = mapped_column(Float, nullable=True)
    dispossessed: Mapped[float | None] = mapped_column(Float, nullable=True)
    chances_created: Mapped[float | None] = mapped_column(Float, nullable=True)
    big_chances_created: Mapped[float | None] = mapped_column(Float, nullable=True)
    defensive_actions: Mapped[float | None] = mapped_column(Float, nullable=True)
    tackles: Mapped[float | None] = mapped_column(Float, nullable=True)
    interceptions: Mapped[float | None] = mapped_column(Float, nullable=True)
    clearances: Mapped[float | None] = mapped_column(Float, nullable=True)
    headed_clearances: Mapped[float | None] = mapped_column(Float, nullable=True)
    recoveries: Mapped[float | None] = mapped_column(Float, nullable=True)
    duels_won: Mapped[float | None] = mapped_column(Float, nullable=True)
    duels_lost: Mapped[float | None] = mapped_column(Float, nullable=True)
    ground_duels_won: Mapped[float | None] = mapped_column(Float, nullable=True)
    aerials_won: Mapped[float | None] = mapped_column(Float, nullable=True)
    dribbles_succeeded: Mapped[float | None] = mapped_column(Float, nullable=True)
    fouls: Mapped[float | None] = mapped_column(Float, nullable=True)
    was_fouled: Mapped[float | None] = mapped_column(Float, nullable=True)
    offsides: Mapped[float | None] = mapped_column(Float, nullable=True)
    dribbled_past: Mapped[float | None] = mapped_column(Float, nullable=True)
    saves: Mapped[float | None] = mapped_column(Float, nullable=True)
    saves_inside_box: Mapped[float | None] = mapped_column(Float, nullable=True)
    goals_conceded: Mapped[float | None] = mapped_column(Float, nullable=True)
    goals_prevented: Mapped[float | None] = mapped_column(Float, nullable=True)
    keeper_diving_saves: Mapped[float | None] = mapped_column(Float, nullable=True)
    keeper_high_claims: Mapped[float | None] = mapped_column(Float, nullable=True)
    keeper_sweeper_actions: Mapped[float | None] = mapped_column(Float, nullable=True)
    punches: Mapped[float | None] = mapped_column(Float, nullable=True)
    errors_led_to_goal: Mapped[float | None] = mapped_column(Float, nullable=True)
    player_throws: Mapped[float | None] = mapped_column(Float, nullable=True)
